name: build-book

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: sudo apt-get update && sudo apt-get install -y texlive-luatex texlive-latex-extra texlive-lang-french latexmk
      - run: make test
      - run: make book
      - uses: actions/upload-artifact@v4
        with:
          name: diderot-ml-book
          path: output/pdf/*.pdf

